from enum import Enum


class ReviewStatus(Enum):
    REVIEW_STATUS_UNSPECIFIED = 'REVIEW_STATUS_UNSPECIFIED'
    UNDER_REVIEW = 'UNDER_REVIEW'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    DRAFT = 'DRAFT'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    EXPIRED = 'EXPIRED'
    INACTIVE = 'INACTIVE'


class BarcodeType(Enum):
    BARCODE_TYPE_UNSPECIFIED = 'BARCODE_TYPE_UNSPECIFIED'
    AZTEC = 'AZTEC'
    CODE_39 = 'CODE_39'
    CODE_128 = 'CODE_128'
    CODABAR = 'CODABAR'
    DATA_MATRIX = 'DATA_MATRIX'
    EAN_8 = 'EAN_8'
    EAN_13 = 'EAN_13'
    ITF_14 = 'ITF_14'
    PDF_417 = 'PDF_417'
    QR_CODE = 'QR_CODE'
    UPC_A = 'UPC_A'
    TEXT_ONLY = 'TEXT_ONLY'


class BarcodeRenderEncoding(Enum):
    RENDER_ENCODING_UNSPECIFIED = 'RENDER_ENCODING_UNSPECIFIED'
    UTF_8 = 'UTF_8'


class DoorsOpenLabel(Enum):
    DOORS_OPEN_LABEL_UNSPECIFIED = 'DOORS_OPEN_LABEL_UNSPECIFIED'
    DOORS_OPEN = 'DOORS_OPEN'
    GATES_OPEN = 'GATES_OPEN'


class MultipleDevicesAndHoldersAllowedStatus(Enum):
    STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED'
    MULTIPLE_HOLDERS = 'MULTIPLE_HOLDERS'
    ONE_USER_ALL_DEVICES = 'ONE_USER_ALL_DEVICES'
    ONE_USER_ONE_DEVICE = 'ONE_USER_ONE_DEVICE'


class ViewUnlockRequirement(Enum):
    VIEW_UNLOCK_REQUIREMENT_UNSPECIFIED = 'VIEW_UNLOCK_REQUIREMENT_UNSPECIFIED'
    UNLOCK_NOT_REQUIRED = 'UNLOCK_NOT_REQUIRED'
    UNLOCK_REQUIRED_TO_VIEW = 'UNLOCK_REQUIRED_TO_VIEW'


class MessageType(Enum):
    MESSAGE_TYPE_UNSPECIFIED = 'MESSAGE_TYPE_UNSPECIFIED'
    TEXT = 'TEXT'
    EXPIRATION_NOTIFICATION = 'EXPIRATION_NOTIFICATION'


class TotpAlgorithm(Enum):
    TOTP_ALGORITHM_UNSPECIFIED = 'TOTP_ALGORITHM_UNSPECIFIED'
    TOTP_SHA1 = 'TOTP_SHA1'


class ScreenshotEligibility(Enum):
    SCREENSHOT_ELIGIBILITY_UNSPECIFIED = 'SCREENSHOT_ELIGIBILITY_UNSPECIFIED'
    ELIGIBLE = 'ELIGIBLE'
    INELIGIBLE = 'INELIGIBLE'


class NfcConstraint(Enum):
    NFC_CONSTRAINT_UNSPECIFIED = 'NFC_CONSTRAINT_UNSPECIFIED'
    BLOCK_PAYMENT = 'BLOCK_PAYMENT'
    BLOCK_CLOSED_LOOP_TRANSIT = 'BLOCK_CLOSED_LOOP_TRANSIT'
