from enum import Enum


class ReviewStatus(Enum):
    REVIEW_STATUS_UNSPECIFIED = 'REVIEW_STATUS_UNSPECIFIED'
    UNDER_REVIEW = 'UNDER_REVIEW'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    DRAFT = 'DRAFT'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    EXPIRED = 'EXPIRED'
    INACTIVE = 'INACTIVE'


class BarcodeType(Enum):
    BARCODE_TYPE_UNSPECIFIED = 'BARCODE_TYPE_UNSPECIFIED'
    AZTEC = 'AZTEC'
    CODE_39 = 'CODE_39'
    CODE_128 = 'CODE_128'
    CODABAR = 'CODABAR'
    DATA_MATRIX = 'DATA_MATRIX'
    EAN_8 = 'EAN_8'
    EAN_13 = 'EAN_13'
    ITF_14 = 'ITF_14'
    PDF_417 = 'PDF_417'
    QR_CODE = 'QR_CODE'
    UPC_A = 'UPC_A'
    TEXT_ONLY = 'TEXT_ONLY'


class BarcodeRenderEncoding(Enum):
    RENDER_ENCODING_UNSPECIFIED = 'RENDER_ENCODING_UNSPECIFIED'
    UTF_8 = 'UTF_8'
